// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaondmtzmfcfvleeythm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhb25kbXR6bWZjZnZsZWV5dGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjA0MzMsImV4cCI6MjA2Nzc5NjQzM30.Gal1lRJ_C-QqzZNcSDDbdRTsDpKoRdT2dAzQPWMK9wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});